apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-function
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: https://github.com/developer-guy/hello-function.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


