apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openfaas
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: apps
    repoURL: https://github.com/developer-guy/hello-function.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
