apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: hellofunction
  namespace: default
spec:
  name: hellofunction
  image: devopps/hello-function:latest@sha256:177061d7fc42a8bcc1fbeded36fc4f50970bcfb716b2b568477147cfc7816754
